[package]
name = "elf_editor"
version = "0.1.0"
authors = ["afal"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf = {path = "../elf" }